'use client';
import type * as THREE from 'three';
import {useEffect,useRef,useState} from 'react';
import type {CountryData} from '@/lib/climate';
import {fmt} from '@/lib/climate';
export type SceneControls={explode:boolean;replay:number;paused:boolean;camera:'atelier'|'plan'|'back';mode:'instrument'|'engine';selected:string|null};
export default function MovementScene({data,controls,onSelect,onReady}:{data:CountryData;controls:SceneControls;onSelect:(id:string)=>void;onReady?:(canvas:HTMLCanvasElement)=>void}){
 const host=useRef<HTMLDivElement>(null);const current=useRef(controls);const select=useRef(onSelect);const ready=useRef(onReady);const [failed,setFailed]=useState(false);
 useEffect(()=>{current.current=controls;select.current=onSelect;ready.current=onReady},[controls,onSelect,onReady]);
 useEffect(()=>{let dispose=()=>{};let cancelled=false;
 void (async()=>{try{
 const T=await import('three');const {RoomEnvironment}=await import('three/addons/environments/RoomEnvironment.js');if(cancelled||!host.current)return;
 const el=host.current;const scene=new T.Scene();const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0x101314,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;el.appendChild(renderer.domElement);ready.current?.(renderer.domElement);
 const pmrem=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
 const camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.set(0,-9.8,12.7);camera.lookAt(0,0,.4);
 const key=new T.DirectionalLight(0xfff3dc,1.9);key.position.set(-3,-4,9);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.bias=-.001;key.shadow.normalBias=.035;scene.add(key);scene.add(new T.AmbientLight(0xc4d4df,.22));
 const world=new T.Group();scene.add(world);world.rotation.z=-.18;
 const grainData=new Uint8Array(256*256*4);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const j=(y*256+x)*4;const g=105+Math.sin(y*2.3)*17+Math.sin(y*.31)*13+Math.sin(x*51.9+y*7.3)*7;grainData[j]=grainData[j+1]=grainData[j+2]=g;grainData[j+3]=255;}const grain=new T.DataTexture(grainData,256,256);grain.wrapS=grain.wrapT=T.RepeatWrapping;grain.repeat.set(2,3);grain.needsUpdate=true;
 const silver=new T.MeshStandardMaterial({color:0x9aa5aa,metalness:.95,roughness:.3,bumpMap:grain,bumpScale:.009});const darkSilver=new T.MeshStandardMaterial({color:0x30373a,metalness:.87,roughness:.34,bumpMap:grain,bumpScale:.015});const pale=new T.MeshStandardMaterial({color:0xaa9c7f,metalness:.87,roughness:.29});const black=new T.MeshStandardMaterial({color:0x171c1f,metalness:.7,roughness:.44});const chrome=new T.MeshStandardMaterial({color:0xe2e8e9,metalness:1,roughness:.17});const glass=new T.MeshPhysicalMaterial({color:0xabc4cf,metalness:.08,roughness:.12,transmission:.62,transparent:true,opacity:.44,thickness:.3,ior:1.45,side:T.DoubleSide,depthWrite:false});const outline=new T.MeshStandardMaterial({color:0x91a1a8,metalness:.65,roughness:.4,transparent:true,opacity:.48});const ruby=new T.MeshPhysicalMaterial({color:0x919ca1,metalness:.7,roughness:.16,clearcoat:1});
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.35}));floor.position.z=-.6;floor.receiveShadow=true;scene.add(floor);
 const groups:THREE.Group[]=[];const moving:{g:THREE.Group;speed:number}[]=[];const hit:THREE.Object3D[]=[];const geo:THREE.BufferGeometry[]=[];
 function mesh(g:THREE.BufferGeometry,m:THREE.Material,p:THREE.Object3D,x=0,y=0,z=0){geo.push(g);const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o;}
 function ring(parent:THREE.Object3D,r:number,w:number,z:number,material:THREE.Material=chrome){return mesh(new T.TorusGeometry(r,w,10,160),material,parent,0,0,z);}
 function disc(parent:THREE.Object3D,r:number,h:number,z:number,material:THREE.Material=silver,x=0,y=0){const o=mesh(new T.CylinderGeometry(r,r,h,96),material,parent,x,y,z);o.rotation.x=Math.PI/2;return o;}
 function annulus(parent:THREE.Object3D,r:number,inner:number,h:number,z:number,material:THREE.Material=silver){const shape=new T.Shape();shape.absarc(0,0,r,0,Math.PI*2,false);const hole=new T.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);shape.holes.push(hole);return mesh(new T.ExtrudeGeometry(shape,{depth:h,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.035,bevelThickness:.025,curveSegments:100}),material,parent,0,0,z);}
 function layer(id:string,z:number){const g=new T.Group();g.position.z=z;g.userData={z,id,index:groups.length};world.add(g);groups.push(g);return g;}
 function attach(o:THREE.Object3D,id:string){o.userData.click=id;hit.push(o);return o;}
 function screw(parent:THREE.Object3D,x:number,y:number,z:number,r=.075){disc(parent,r,.06,z,chrome,x,y);const cut=mesh(new T.BoxGeometry(r*1.5,.016,.008),black,parent,x,y,z+.034);cut.rotation.z=.6;}
 function ticks(parent:THREE.Object3D,r:number,z:number,n=120){const geom=new T.BoxGeometry(.016,.08,.014);geo.push(geom);const inst=new T.InstancedMesh(geom,chrome,n);const obj=new T.Object3D();for(let i=0;i<n;i++){const a=i/n*Math.PI*2;obj.position.set(Math.sin(a)*r,Math.cos(a)*r,z);obj.rotation.z=-a;obj.scale.y=i%5===0?2.5:1;obj.updateMatrix();inst.setMatrixAt(i,obj.matrix);}parent.add(inst);}
 function cog(parent:THREE.Object3D,x:number,y:number,r:number,teeth:number,mat:THREE.Material,phase=0){const g=new T.Group();g.position.set(x,y,0);parent.add(g);const shape=new T.Shape();const mod=r/teeth;for(let i=0;i<teeth*4;i++){const a=i/(teeth*4)*Math.PI*2;const rr=i%4===1||i%4===2?r+mod:r-mod;const px=Math.cos(a)*rr,py=Math.sin(a)*rr;if(i===0)shape.moveTo(px,py);else shape.lineTo(px,py);}shape.closePath();const center=new T.Path();center.absarc(0,0,r*.22,0,Math.PI*2,true);shape.holes.push(center);for(let j=0;j<5;j++){const a=j/5*Math.PI*2;const h=new T.Path();h.absarc(Math.cos(a)*r*.58,Math.sin(a)*r*.58,r*.20,0,Math.PI*2,true);shape.holes.push(h);}mesh(new T.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:true,bevelThickness:.016,bevelSize:.015,bevelSegments:2,curveSegments:24}),mat,g);ring(g,r*.26,.025,.14,chrome);disc(g,r*.12,.24,.12,darkSilver);screw(g,0,0,.28,r*.07);g.rotation.z=phase;moving.push({g,speed:(moving.length%2===0?1:-1)*.45/teeth*40});return g;}
 function bar(parent:THREE.Object3D,a:[number,number],b:[number,number],w:number,z:number){const dx=b[0]-a[0],dy=b[1]-a[1];const len=Math.hypot(dx,dy);const s=new T.Shape();s.moveTo(-w/2,-len/2);s.lineTo(w/2,-len/2);s.lineTo(w/2,len/2);s.absarc(0,len/2,w/2,0,Math.PI,false);s.lineTo(-w/2,-len/2);s.absarc(0,-len/2,w/2,Math.PI,Math.PI*2,false);const o=mesh(new T.ExtrudeGeometry(s,{depth:.12,bevelEnabled:true,bevelSize:.06,bevelThickness:.035,bevelSegments:3}),silver,parent,(a[0]+b[0])/2,(a[1]+b[1])/2,z);o.rotation.z=-Math.atan2(dx,dy);screw(parent,...a,z+.18,.085);screw(parent,...b,z+.18,.085);return o;}
 const base=layer('base',0);annulus(base,3.08,.90,.22,-.28,darkSilver);annulus(base,3.16,2.89,.18,-.30,black);ring(base,3.13,.035,-.07,chrome);ring(base,3.02,.028,-.05,silver);ring(base,2.9,.018,-.015,pale);disc(base,.9,.17,-.2,black);
 for(let j=0;j<24;j++){const a=j/24*Math.PI*2;disc(base,.11,.04,-.02,black,Math.sin(a)*2.74,Math.cos(a)*2.74);if(j%3===0)screw(base,Math.sin(a)*2.94,Math.cos(a)*2.94,.05,.07);}
 // Cut silver bearings, concentric machining, and skeleton gear train.
 const gearLayer=layer('delivery',.13);const gearSpec:[number,number,number,number,THREE.Material][]=[[-1.02,-.32,.87,36,pale],[.56,-.32,.70,29,silver],[1.25,.76,.58,24,pale],[-.48,1.07,.59,24,silver],[-1.49,1.12,.41,17,pale],[.31,-1.50,.51,21,silver],[1.42,-1.47,.53,22,darkSilver],[-1.49,-1.73,.43,18,silver]];
 gearSpec.forEach(([x,y,r,t,m],i)=>{disc(gearLayer,r*.25,.17,-.02,black,x,y);attach(cog(gearLayer,x,y,r,t,m,i*.11),'delivery');});
 const bridge=layer('evidence',.62);attach(bar(bridge,[-1.02,-.32],[-1.49,-1.73],.30,0),'evidence');attach(bar(bridge,[-.48,1.07],[1.25,.76],.32,0),'evidence');bar(bridge,[.56,-.32],[1.42,-1.47],.26,.01);ring(bridge,.72,.045,.01,silver).position.set(-1.02,-.32,.01);
 // Evidence bearings encode reported / promised / unparsed / confirmed absent independently.
 const jewels=layer('jewels',.73);Object.entries(data.btr.components).forEach(([key,c],i)=>{const a=(i/8)*Math.PI*2;const x=Math.sin(a)*2.25,y=Math.cos(a)*2.25;const g=new T.Group();g.position.set(x,y,0);jewels.add(g);const o=ring(g,.105,c.state==='unknown'?.012:.026,0,c.state==='absent'?black:chrome);attach(o,'evidence');if(c.state==='observed')disc(g,.08,.065,.012,ruby);if(c.state==='pledged')disc(g,.08,.065,.012,glass);if(c.state==='absent')disc(g,.083,.07,-.045,black);g.userData.key=key;});
 const chapter=layer('pledge',.85);attach(annulus(chapter,2.97,2.49,.045,0,glass),'pledge');ring(chapter,2.99,.017,.07,chrome);ring(chapter,2.47,.012,.055,outline);ticks(chapter,2.82,.08);const pct=data.ndc.reduction_pct;
 if(pct!=null){const arc=new T.Mesh(new T.TorusGeometry(2.62,.044,12,150,Math.PI*2*pct/100),glass);arc.rotation.z=Math.PI*.50;arc.position.z=.09;chapter.add(arc);geo.push(arc.geometry);attach(arc,'pledge');for(const a of [Math.PI*.5,Math.PI*.5+Math.PI*2*pct/100]){disc(chapter,.062,.06,.105,chrome,Math.cos(a)*2.62,Math.sin(a)*2.62);}}
 // Emissions are radial data marks. A single observation never becomes an invented trajectory.
 const values=[...data.series.observed,...data.series.target,...data.series.bau].map(p=>p.value_mtco2e);const max=Math.max(...values,1);const radius=(v:number)=>1.9+.70*v/max;const angle=(year:number)=>Math.PI*.8+Math.PI*1.4*(year-(data.ndc.base_year??2005))/Math.max(1,(data.ndc.target_year??2030)-(data.ndc.base_year??2005));
 const plots=layer('trajectory',1.02);for(const [key,pts,mat] of [['observed',data.series.observed,chrome],['target',data.series.target,glass]] as const){const vs=pts.map(p=>new T.Vector3(Math.cos(angle(p.year))*radius(p.value_mtco2e),Math.sin(angle(p.year))*radius(p.value_mtco2e),.02));vs.forEach(v=>{const o=disc(plots,key==='observed'?.077:.055,.025,v.z,mat,v.x,v.y);attach(o,'delivery')});if(vs.length>1){const curve=new T.CatmullRomCurve3(vs);attach(mesh(new T.TubeGeometry(curve,80,.018,6,false),mat,plots),'delivery');}}
 const conditional=layer('conditions',.45);conditional.position.x=3.43;conditional.position.y=1.03;conditional.userData.floating=true;const cg=cog(conditional,0,0,.57,24,glass);attach(cg,'conditions');moving.pop();ring(conditional,.64,.008,.17,outline);disc(conditional,.14,.1,.15,glass);ring(conditional,.18,.013,.2,chrome);
 // Dashed tether means a dependency, never an inferred finance fulfilment rate.
 const tetherGeo=new T.BufferGeometry().setFromPoints([new T.Vector3(2.62,1.03,.52),new T.Vector3(2.92,1.03,.52)]);geo.push(tetherGeo);const tether=new T.Line(tetherGeo,new T.LineDashedMaterial({color:0x91a1a8,dashSize:.06,gapSize:.08}));tether.computeLineDistances();world.add(tether);
 const hub=layer('hub',.65);disc(hub,.41,.07,.1,black);ring(hub,.42,.018,.15,chrome);disc(hub,.12,.1,.17,pale);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const o=mesh(new T.BoxGeometry(.02,.13,.02),silver,hub,Math.sin(a)*.26,Math.cos(a)*.26,.17);o.rotation.z=-a;}
 // Forty slots represent the declared source catalog, with no fabricated run activity.
 const engine=layer('sources',-.13);for(let i=0;i<40;i++){const a=i/40*Math.PI*2;const g=new T.Group();g.position.set(Math.sin(a)*3.65,Math.cos(a)*3.65,0);engine.add(g);g.userData.sourceIndex=i;disc(g,.15,.22,0,darkSilver);ring(g,.15,.015,.12,silver);screw(g,0,0,.14,.055);attach(g,'sources');}engine.visible=current.current.mode==='engine';
 const conduits=new T.Group();engine.add(conduits);for(let i=0;i<40;i++){const a=i/40*Math.PI*2;const path=new T.CatmullRomCurve3([new T.Vector3(Math.sin(a)*3.49,Math.cos(a)*3.49,.02),new T.Vector3(Math.sin(a)*3.23,Math.cos(a)*3.23,.16),new T.Vector3(Math.sin(a)*2.94,Math.cos(a)*2.94,.20)]);mesh(new T.TubeGeometry(path,10,.012,5,false),darkSilver,conduits);}
 // A subtle real request pulse is shown only for the initial load / new country response.
 const pulseMat=new T.MeshStandardMaterial({color:0xff8a3d,emissive:0xff722e,emissiveIntensity:2});const pulse=mesh(new T.SphereGeometry(.045,12,12),pulseMat,world);pulse.visible=false;
 let disposed=false,raf=0,last=performance.now(),start=last,elapsed=0;let replay=current.current.replay;let burst=0;let modeScale=1;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let hasVisited=false;try{hasVisited=sessionStorage.getItem('vc-assembled')==='yes';sessionStorage.setItem('vc-assembled','yes')}catch{}if(hasVisited||reduced.matches)start-=5000;
 const pointer=new T.Vector2(),raycaster=new T.Raycaster();const click=(e:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const intersects=raycaster.intersectObjects(hit.filter(o=>{let p:THREE.Object3D|null=o;while(p){if(!p.visible)return false;p=p.parent;}return true}),true);if(intersects.length){let o:THREE.Object3D|null=intersects[0].object;while(o&&!o.userData.click)o=o.parent;if(o)select.current(o.userData.click);}};renderer.domElement.addEventListener('pointerup',click);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const ease=(t:number)=>1-Math.pow(1-Math.max(0,Math.min(t,1)),4);
 const look=new T.Vector3(0,0,.25);const targetPos=new T.Vector3();
 function frame(now:number){if(disposed)return;raf=requestAnimationFrame(frame);if(document.hidden){last=now;return;}const dt=Math.min((now-last)/1000,.05);last=now;const c=current.current;const still=reduced.matches;const rate=still?1:1-Math.exp(-dt*7);if(c.replay!==replay){replay=c.replay;start=now;elapsed=0;}if(!c.paused&&!still)elapsed+=dt;const time=(now-start)/1000;const ex=c.explode?1:0;burst+=(ex-burst)*rate;const scale=c.mode==='engine'?.89:1;modeScale+=(scale-modeScale)*rate;world.scale.setScalar(modeScale);engine.visible=c.mode==='engine';engine.children.forEach((g,j)=>{const seat=still?1:ease((time-.1-j*.035)/.75);g.position.z=(1-seat)*3;});
 groups.forEach((g,i)=>{const order:Record<string,number>={base:0,pledge:1,conditions:2,delivery:3,trajectory:4,evidence:5,jewels:6,hub:7,sources:0};const seat=still?1:ease((time-.13-(order[g.userData.id]??i)*.20)/.85);g.position.z=g.userData.z+(1-seat)*(4+i*.15)+burst*(i*.29);g.visible=seat>.01&&(g!==engine||c.mode==='engine');if(g.userData.floating)g.position.z+=still?0:Math.sin(elapsed*1.3)*.05;});
 moving.forEach(({g,speed})=>{if(!c.paused&&!still)g.rotation.z+=dt*speed*.32;});
 if(c.camera==='plan')targetPos.set(0,-.001,17);else if(c.camera==='back')targetPos.set(0,8,12);else targetPos.set(0,-9.8,12.7);if(c.explode)targetPos.multiplyScalar(1.15);camera.position.lerp(targetPos,rate);camera.lookAt(look);
 pulse.visible=time<2.7&&time>.3&&!still&&!c.paused;if(pulse.visible){const a=time*3; pulse.position.set(Math.cos(a)*2.72,Math.sin(a)*2.72,.97);}
 renderer.render(scene,camera);
 }
 raf=requestAnimationFrame(frame);
 dispose=()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();renderer.domElement.removeEventListener('pointerup',click);const materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof T.Mesh){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));o.geometry.dispose();}if(o instanceof T.Line){o.geometry.dispose();materials.add(o.material as THREE.Material)}});materials.forEach(m=>m.dispose());geo.forEach(g=>g.dispose());grain.dispose();env.dispose();renderer.dispose();renderer.domElement.remove();};
 }catch(e){console.error('Movement renderer unavailable',e);setFailed(true);}})();return()=>{cancelled=true;dispose();};
 },[data]);
 return <div className="scene-host" ref={host} aria-label={`${data.country.name_en} climate movement. Target reduction ${fmt(data.ndc.reduction_pct)} percent. ${data.series.observed.length} observations. Evidence components are individually labelled below.`}>{failed&&<div className="fallback"><StaticDial data={data}/><p>3D is unavailable on this device. All evidence remains accessible below.</p></div>}</div>;
}
export function StaticDial({data}:{data:CountryData}){const pct=data.ndc.reduction_pct??0;return <svg viewBox="0 0 420 420" aria-label="Static climate evidence dial"><circle cx="210" cy="210" r="185" fill="#181e20" stroke="#79868b"/><circle cx="210" cy="210" r="163" fill="none" stroke="#303a3f" strokeWidth="20"/><circle cx="210" cy="210" r="163" fill="none" stroke="#abc4cf" strokeWidth="12" strokeDasharray={`${pct/100*1024} 1024`} transform="rotate(-90 210 210)"/>{Object.entries(data.btr.components).map(([k,v],i)=>{const a=i/8*Math.PI*2;return <circle key={k} cx={210+100*Math.cos(a)} cy={210+100*Math.sin(a)} r="9" fill={v.state==='observed'?'#bcc7cb':v.state==='absent'?'#08090a':'none'} stroke={v.state==='absent'?'#bf6461':'#76878e'} strokeDasharray={v.state==='unknown'?'2 3':undefined}/>})}<text x="210" y="203" textAnchor="middle" fill="#eef0e9" fontSize="42" fontFamily="serif">{fmt(data.ndc.reduction_pct)}%</text><text x="210" y="230" textAnchor="middle" fill="#9bacb3" fontSize="12">PLEDGED REDUCTION</text></svg>}
