import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import {loadView} from '@/lib/record';

// P6, the Refusal Log. Every calculation the engine declined, in its own words.
// Server-rendered and grouped with <details>, so the whole log is in the HTML
// for a reader, a crawler or a filing — there is no client state to lose.
export const metadata:Metadata={
 title:'The Refusal Log — Visual Climate',
 description:'Every calculation this engine declined to make, in its own words, grouped by why. A refusal is an output, not a failure.',
};

type Entry={iso3:string;name_en:string;reason:string};
type Family={id:string;field:string;label:string;note:string;count:number;entries:Entry[]};
type Log={total:number;distinct_sentences:number;by_field:{field:string;count:number}[];families:Family[]};

export default async function Page(){
 const log=await loadView<Log>('refusals');
 return <main className="record">
  <header className="rec-top"><Link className="rec-back" href="/"><ArrowLeft size={15}/> The instrument</Link><Link className="rec-contract" href="/divergence">Divergence Atlas <ArrowUpRight size={13}/></Link></header>
  <div className="rec-shell">
   <section className="rec-head">
    <p className="eyebrow"><span className="index">P6</span> THE REFUSAL LOG</p>
    <h1 className="rec-title">What the engine would not compute<span className="rec-stop">.</span></h1>
    <p className="rec-lede">Every sentence below was generated by a rule in <code>engine/build/derive.ts</code> or <code>engine/sources/ds-06-ndc-docs.ts</code> at build time, not written by a model and not written by hand. A refusal is an output of this product, not a gap in it: it says exactly which evidence is missing, so a reader can go and check whether we were right to stop.</p>
   </section>

   {!log?<div className="rec-blank"><span className="state-token unknown"><i/>Log unavailable</span><p>The refusal log has not been published with this build. Run <code>npm run engine:index</code> and redeploy.</p></div>:<>
    <section className="rec-tiles">
     <div className="rec-tile"><span className="rec-tile-label">Refusals</span><strong>{log.total}</strong><small>calculations declined</small></div>
     <div className="rec-tile"><span className="rec-tile-label">Distinct sentences</span><strong>{log.distinct_sentences}</strong><small>364 refusals, {log.distinct_sentences} wordings between them</small></div>
     <div className="rec-tile"><span className="rec-tile-label">Reasons</span><strong>{log.families.length}</strong><small>families of refusal</small></div>
     {log.by_field.map(f=><div className="rec-tile" key={f.field}><span className="rec-tile-label">{f.field}</span><strong>{f.count}</strong><small>refusals from this field</small></div>)}
    </section>

    <section className="rec-section" id="reasons">
     <h2><i>01</i> By reason</h2>
     <p className="rec-note">Open a family to read every country it covers, with that country&rsquo;s own sentence. Nothing is truncated: the sentence in the log is byte-identical to the one in the record.</p>
     <div className="refusal-list">
      {log.families.map(f=><details className="refusal" key={f.id} open={f.count>=100}>
       <summary><b>{f.label}</b><span className="refusal-count">{f.count}</span><code>{f.field}</code></summary>
       <p className="rec-note">{f.note}</p>
       <ol className="refusal-entries">
        {f.entries.map(e=><li key={e.iso3}><Link href={`/country/${e.iso3}`}><i>{e.iso3}</i>{e.name_en}</Link><p>{e.reason}</p></li>)}
       </ol>
      </details>)}
     </div>
    </section>
   </>}
  </div>
 </main>;
}
