import type {Metadata} from 'next';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import {loadView} from '@/lib/record';

// P6, the Refusal Log. Every calculation the engine declined, in its own words.
// Server-rendered and grouped with <details>, so the whole log is in the HTML
// for a reader, a crawler or a filing, there is no client state to lose.
export const metadata:Metadata={
 title:'The Refusal Log, Visual Climate',
 description:'Every calculation this engine declined to make, in its own words, grouped by why. A refusal is an output, not a failure.',
};

type Entry={iso3:string;name_en:string;reason:string};
type Family={id:string;field:string;label:string;note:string;count:number;entries:Entry[]};
type Log={total:number;distinct_sentences:number;by_field:{field:string;count:number}[];families:Family[]};

export default async function Page(){
 const log=await loadView<Log>('refusals');
 // Lead with a real one, picked by rule so it is never cherry-picked: the
 // longest sentence that is actually about evidence. Toolchain failures are
 // excluded, they describe our build, not the country's filing, and a raw
 // shell error is exactly the thing that must never reach a reader.
 const aboutEvidence=(r:string)=>!/could not be read|extractor|command failed|<path>/i.test(r);
 const specimen=log?.families.map(f=>f.entries.find(e=>aboutEvidence(e.reason))).filter(Boolean)
  .sort((a,b)=>b!.reason.length-a!.reason.length)[0];
 return <main className="record" id="main">
    <div className="rec-shell">
   <section className="ref-masthead">
    <p className="eyebrow">THE REFUSAL LOG</p>
    <h1 className="rec-title">What the engine would not compute<span className="rec-stop">.</span></h1>
    {specimen&&<figure className="ref-specimen">
     <blockquote>{specimen.reason}</blockquote>
     <figcaption>
      <a href={`/country/${specimen.iso3}`}><i>{specimen.iso3}</i>{specimen.name_en}</a>
      <span>one of {log?.total} refusals · {log?.distinct_sentences} distinct wordings</span>
     </figcaption>
    </figure>}
    <p className="rec-lede">Every sentence here was generated by a rule in <code>engine/build/derive.ts</code> or <code>engine/sources/ds-06-ndc-docs.ts</code> at build time, not written by a model, not written by hand. A refusal is an output of this product, not a gap in it: it names the missing evidence, so a reader can check whether we were right to stop.</p>
   </section>

   {!log?<div className="rec-blank"><span className="state-token unknown"><i/>Log unavailable</span><p>The refusal log has not been published with this build. Run <code>npm run engine:index</code> and redeploy.</p></div>:<>
    <section className="rec-tiles">
     <div className="rec-tile"><span className="rec-tile-label">Refusals</span><strong>{log.total}</strong><small>calculations declined</small></div>
     <div className="rec-tile"><span className="rec-tile-label">Distinct sentences</span><strong>{log.distinct_sentences}</strong><small>364 refusals, {log.distinct_sentences} wordings between them</small></div>
     <div className="rec-tile"><span className="rec-tile-label">Reasons</span><strong>{log.families.length}</strong><small>families of refusal</small></div>
     {log.by_field.map(f=><div className="rec-tile" key={f.field}><span className="rec-tile-label">{f.field}</span><strong>{f.count}</strong><small>refusals from this field</small></div>)}
    </section>

    <section className="rec-section" id="reasons">
     <h2>By reason</h2>
     <p className="rec-note">Open a family to read every country it covers, with that country&rsquo;s own sentence. Nothing is truncated: the sentence in the log is byte-identical to the one in the record.</p>
     <div className="refusal-list">
      {log.families.map(f=><details className="refusal" key={f.id} open={f.count>=100}>
       <summary><b>{f.label}</b><span className="refusal-count">{f.count}</span><code>{f.field}</code></summary>
       <p className="rec-note">{f.note}</p>
       <ol className="refusal-entries">
        {f.entries.map(e=><li key={e.iso3}><a href={`/country/${e.iso3}`}><i>{e.iso3}</i>{e.name_en}</a><p>{e.reason}</p></li>)}
       </ol>
      </details>)}
     </div>
    </section>
   </>}
  </div>
 </main>;
}
