import type {Metadata} from 'next';
import {loadView} from '@/lib/record';
import RefusalBrowser,{type Log} from '@/components/refusals/refusal-browser';

// P6, the Refusal Log. Every calculation the engine declined, in its own words.
// The sentences are server-rendered into the HTML; the browser on top of them
// filters, searches and exports what is already there.
export const metadata:Metadata={
 title:'The Refusal Log, Visual Climate',
 description:'Every calculation this engine declined to make, in its own words, grouped by why. A refusal is an output, not a failure.',
};

export default async function Page(){
 const log=await loadView<Log>('refusals');
 // Lead with a real one, picked by rule so it is never cherry-picked: the
 // longest sentence that is actually about evidence. Toolchain failures are
 // excluded, they describe our build, not the country's filing.
 const aboutEvidence=(r:string)=>!/could not be read|extractor|command failed|<path>/i.test(r);
 const specimen=log?.families.map(f=>f.entries.find(e=>aboutEvidence(e.reason))).filter(Boolean)
  .sort((a,b)=>b!.reason.length-a!.reason.length)[0];
 const byField=Object.fromEntries((log?.by_field??[]).map(f=>[f.field,f.count]));
 return <main className="record" id="main">
  <div className="rec-shell">
   <section className="ref-masthead">
    <p className="eyebrow">THE REFUSAL LOG</p>
    <h1 className="rec-title">What the engine would not compute<span className="rec-stop">.</span></h1>
    {specimen&&<figure className="ref-specimen reveal">
     <blockquote>{specimen.reason}</blockquote>
     <figcaption>
      <a href={`/country/${specimen.iso3}`}><i>{specimen.iso3}</i>{specimen.name_en}</a>
      <span>one of {log?.total} refusals · {log?.distinct_sentences} distinct wordings</span>
     </figcaption>
    </figure>}
    <details className="disc">
     <summary>Why a refusal is an output, not a gap</summary>
     <div className="disc-body">Every sentence here was generated by a rule in <code>engine/build/derive.ts</code> or <code>engine/sources/ds-06-ndc-docs.ts</code> at build time, not written by a model and not written by hand. It names the evidence that was missing, so a reader can check whether we were right to stop. The sentence in this log is byte-identical to the one in the country&rsquo;s record and in the API payload.</div>
    </details>
   </section>
  </div>

  {!log?<div className="rec-shell"><div className="rec-blank"><span className="state-token unknown"><i/>Log unavailable</span><p>The refusal log has not been published with this build. Run <code>npm run engine:index</code> and redeploy.</p></div></div>:<>
   <section className="kpi-band" aria-label="The log in four figures">
    <div className="kpi"><strong className="kpi-fig countup">{log.total}</strong><span className="kpi-lab">Calculations refused</span><span className="kpi-sub">each one with the sentence that says why</span></div>
    <div className="kpi"><strong className="kpi-fig countup">{log.distinct_sentences}</strong><span className="kpi-lab">Distinct wordings</span><span className="kpi-sub">no two countries share a reason by accident</span></div>
    <div className="kpi"><strong className="kpi-fig countup">{log.families.length}</strong><span className="kpi-lab">Families of refusal</span><span className="kpi-sub">every sentence lands in one; none are unclassified</span></div>
    <div className="kpi"><strong className="kpi-fig countup">{byField['derived.$reason']??0}</strong><span className="kpi-lab">From the ambition gap</span><span className="kpi-sub">{byField['ndc_document.$reason']??0} more from reading the filings</span></div>
   </section>

   <section className="band raised" id="reasons">
    <div className="sec-head warn">
     <h2>Filter the log</h2>
     <p>Pick why, or search the sentences. Open a row to read it whole.</p>
    </div>
    <RefusalBrowser log={log}/>
   </section>
  </>}
 </main>;
}
