import { ArrowLeft, CheckCircle2, ClipboardCheck, LockKeyhole, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export default function Admin() {
  const { user, loading } = useAuth();
  const capabilities = trpc.climate.capabilities.useQuery(undefined, { enabled: Boolean(user) });
  const audit = trpc.account.auditLogs.useQuery(undefined, { enabled: Boolean(user && user.role === "admin") });
  if (loading) return <div className="min-h-screen bg-[#111614] p-10 text-[#91a69d]">Checking access…</div>;
  if (!user) return <div className="vc-shell min-h-screen p-10"><Link href="/" className="flex items-center gap-2 text-sm text-[#91a69d]"><ArrowLeft size={16} /> Back</Link><div className="mx-auto mt-24 max-w-md rounded-2xl border border-white/10 bg-[#1b2420] p-8 text-center"><LockKeyhole className="mx-auto text-[#ffb765]" size={28} /><h1 className="mt-4 text-xl font-bold">Sign in required</h1><p className="mt-2 text-xs leading-5 text-[#91a69d]">The operations console is restricted to authenticated users.</p></div></div>;
  return <div className="vc-shell min-h-screen"><header className="flex items-center justify-between border-b border-white/[.08] px-5 py-5 sm:px-10"><Link href="/" className="flex items-center gap-2 text-sm text-[#91a69d]"><ArrowLeft size={16} /> Explore</Link><div className="vc-label">Platform operations</div></header><main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10"><div className="vc-label text-[#75d5c8]">VisualClimateAgent · Control plane</div><h1 className="mt-3 text-5xl font-extrabold tracking-[-.07em]">Trust is<br /><span className="text-[#75d5c8]">observable.</span></h1><div className="mt-10 grid gap-6 lg:grid-cols-2"><section className="vc-card rounded-2xl p-6"><div className="flex items-center gap-3"><ClipboardCheck className="text-[#75d5c8]" size={19} /><h2 className="text-xl font-bold">Quality gate contract</h2></div><div className="mt-5 space-y-3">{capabilities.data?.qualityGates.map(([id, label, detail]) => <div key={id} className="rounded-xl border border-white/[.08] p-3"><div className="flex items-center gap-2 text-xs font-bold"><span className="vc-mono text-[#75d5c8]">{id}</span><span>{label}</span><CheckCircle2 className="ml-auto text-[#75d5c8]" size={14} /></div><div className="mt-1 text-[10px] leading-4 text-[#91a69d]">{detail}</div></div>)}</div></section><section className="vc-card rounded-2xl p-6"><div className="flex items-center gap-3"><ShieldAlert className="text-[#ffb765]" size={19} /><h2 className="text-xl font-bold">16 skill registry</h2></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{capabilities.data?.skills.map(([id, name, detail]) => <div key={id} className="rounded-xl bg-white/[.03] p-3"><div className="vc-mono text-[10px] text-[#75d5c8]">{id}</div><div className="mt-1 text-xs font-bold">{name}</div><div className="mt-1 text-[10px] leading-4 text-[#91a69d]">{detail}</div></div>)}</div></section></div><section className="vc-card mt-6 rounded-2xl p-6"><h2 className="text-xl font-bold">Recent audit events</h2>{user.role !== "admin" ? <p className="mt-3 text-xs text-[#91a69d]">Reviewer or platform-admin permission is required to view audit events.</p> : <div className="mt-4 space-y-2">{audit.data?.map((event) => <div key={event.id} className="grid gap-2 rounded-xl border border-white/[.08] p-3 text-xs sm:grid-cols-[100px_100px_1fr_100px]"><span className="vc-mono text-[#75d5c8]">{event.runId.slice(0, 10)}</span><span>{event.subagentId}</span><span className="text-[#91a69d]">{event.action}</span><span className="text-[#75d5c8]">{event.status}</span></div>)}</div>}</section></main></div>;
}
