import { AlertTriangle, ArrowRight, CheckCircle2, Info, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import EditorialShell from "@/components/EditorialShell";
import { trpc } from "@/lib/trpc";

export default function Verify() {
  const params = new URLSearchParams(window.location.search);
  const input = { country: params.get("country") ?? "KHM", yearStart: Number(params.get("yearStart") ?? 2015), yearEnd: Number(params.get("yearEnd") ?? 2023), metric: params.get("metric") ?? "Total GHG emissions", sector: params.get("sector") ?? "All sectors", gas: params.get("gas") ?? "All gases" };
  const { data, isLoading, isError, refetch } = trpc.climate.verify.useQuery(input);
  if (isLoading) return <EditorialShell eyebrow="04 · VERIFY / LOADING"><div className="loading-state">Running source comparability checks…</div></EditorialShell>;
  if (isError || !data) return <EditorialShell eyebrow="04 · VERIFY / ERROR"><div className="empty-state"><AlertTriangle size={18} /><span>Verification could not be completed.</span><button className="button-secondary" onClick={() => refetch()}>Retry</button></div></EditorialShell>;
  const first = data.values[0];
  const second = data.values[1];
  const checks = [
    { label: "GWP basis", status: "warn", detail: "The selected inventory sources declare different or incomplete GWP conventions; absolute values require a boundary note." },
    { label: "Boundary", status: "warn", detail: `${input.sector} and ${input.gas} are retained as query conditions; source-level coverage must still be checked.` },
    { label: "Reference period", status: input.yearStart <= input.yearEnd ? "pass" : "fail", detail: `${input.yearStart}–${input.yearEnd} is the retained observation window.` },
    { label: "Uncertainty", status: first?.uncertainty ? "pass" : "warn", detail: first?.uncertainty ? `Reported as ${first.uncertainty}.` : "No quantitative uncertainty was declared by the selected source." },
    { label: "Provenance", status: data.metadata.dataMode === "SIMULATED_DEMO" ? "warn" : "pass", detail: data.metadata.provenance },
  ];
  const verificationHref = `/query`;
  return <EditorialShell eyebrow="04 · VERIFY / EXPLAIN DIFFERENCES"><div className="page-intro"><div><div className="section-kicker">CROSS-SOURCE VERIFICATION</div><h1>Do the sources<br /><em>actually agree?</em></h1><p>Verification is a separate step from retrieval. It explains disagreement before a user turns it into a conclusion.</p></div><Link href={verificationHref} className="text-link">Change conditions <ArrowRight size={14} /></Link></div>
    <section className="verification-summary editorial-panel"><div className="panel-heading"><div><span className="section-number">01</span><h2>Verification target</h2></div><span className="status-pill status-warn"><AlertTriangle size={13} /> review required</span></div><div className="target-grid"><div><span>Country</span><strong>{data.country.name} ({data.country.iso3})</strong></div><div><span>Indicator</span><strong>{input.metric}</strong></div><div><span>Reference period</span><strong>{input.yearStart}–{input.yearEnd}</strong></div><div><span>Conditions</span><strong>{input.sector} · {input.gas}</strong></div></div></section>
    <section className="verification-layout"><div><div className="section-heading compact"><div><div className="section-kicker">02 · SOURCE COMPARISON</div><h2>Same question, different instruments.</h2></div></div><div className="source-cards">{data.values.map((citation) => <div className="source-card" key={citation.id}><div><span className="source-id">{citation.id}</span><h3>{citation.name}</h3></div><strong>{citation.value.toFixed(1)}<small> {citation.unit}</small></strong><div className="source-details"><span>Reference {citation.year}</span><span>{citation.uncertainty ?? "Uncertainty not declared"}</span><span>{citation.id === first?.id ? "reference source" : `${citation.differenceFromFirst > 0 ? "+" : ""}${citation.differenceFromFirst}% vs first source`}</span></div><div className="source-state"><CheckCircle2 size={13} /> source metadata retained</div></div>)}</div><div className="methodology-note"><Info size={15} /><div><strong>Demo data disclosure.</strong> {data.metadata.provenance}</div></div></div><aside className="explain-panel"><div className="panel-kicker"><Info size={14} /> QUALITY REVIEW</div><h2>Difference is information.</h2><p>IPCC-style uncertainty reporting and UNFCCC-style transparency require the source, method, coverage, and limitations to travel with the number.</p><div className="check-list">{checks.map((check) => <div key={check.label}><span className={`check ${check.status === "pass" ? "pass" : check.status === "warn" ? "warn" : "fail"}`}>{check.status === "pass" ? <CheckCircle2 size={13} /> : <AlertTriangle size={13} />}</span><div><strong>{check.label}</strong><p>{check.detail}</p></div></div>)}</div><div className="recommendation"><ShieldCheck size={15} /><div><strong>Recommended next step</strong><p>{second ? `Use the ${first?.name}–${second.name} direction only after retaining the ${Math.abs(second.differenceFromFirst)}% source difference.` : "Add an independent source before making a comparison claim."}</p></div></div></aside></section></EditorialShell>;
}
